global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fractiai'
    static_configs:
      - targets: ['fractiai-api:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'fractiai-worker'
    static_configs:
      - targets: ['fractiai-worker:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] 